services:
  - type: web
    name: whisper-api
    env: python
    buildCommand: "./.render-build.sh"
    startCommand: "npm start"
    runtime: node
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
